### ISSUE TITLE
Create GithubApp to avoid needing the GITHUB_TOKEN from the action.  

### ISSUE THREAD

**Issue by gagoar** [gagoar/use-herald-action#58]
- Add herald GitHub app to avoid asking for the secret in the PR configuration. (leave it optional)
- Add documentation to install the GitHub app.

**Comment by gagoar** [comment]
Due to how GithubApps work. we are not gonna be able to have a generic GithubApp without having a server-side component to keep secrets (particularly the private key) so I think we should use #83 and add Documentation in how to set up a GithubApp in an organization if the user wishes to have it. This will be helpful particularly to private organizations

**Comment by cyamonide** [comment]
Ran across this just now: https://docs.github.com/en/developers/apps/creating-a-github-app-from-a-manifest

At first glance, it looks like a blueprint we can distribute so that users can setup a local (to their organization) instance of whatever app we specify in the manifest.

I haven't dug deeper yet - lmk what you think about this.

**Comment by cyamonide** [comment]
> Ran across this just now: https://docs.github.com/en/developers/apps/creating-a-github-app-from-a-manifest
> 
> At first glance, it looks like a blueprint we can distribute so that users can setup a local (to their organization) instance of whatever app we specify in the manifest.
> 
> I haven't dug deeper yet - lmk what you think about this.

Going to put #83 on pause for now, since taking advantage of app manifests may replace a majority of the docs requested in the ticket.

**Comment by gagoar** [comment]
oh wow, gamechanger for this. sounds like an amazing way of solving the problem. there might be light at the end of this tunnel after all :)

**Comment by gagoar** [comment]
I'm removing the tag from this version given that is gonna happen outside the versioning

**Comment by cyamonide** [comment]
Currently blocked by a GitHub support ticket about the app manifest verification endpoint (unsure if this is visible to the public, but here it is: https://support.github.com/ticket/personal/0/828093)

**Comment by gagoar** [comment]
> Currently blocked by a GitHub support ticket about the app manifest verification endpoint (unsure if this is visible to the public, but here it is: https://support.github.com/ticket/personal/0/828093)

I don't think this  link works for other than you afaik (`personal/`)

**Comment by cyamonide** [comment]
Update on the ticket - it's been resolved and I'm unblocked from completing the post-setup flow 😎

**Comment by cyamonide** [comment]
Response from support:
> I found the HTTP 500 errors you were experiencing in our logs and it appears this was due to an issue on our end specifically for manifests that didn't contain a webhook.
> 
> One of our engineers closed this hole a few hours ago and you shouldn't be seeing those 500s anymore. Can I ask you to confirm?

**Comment by gagoar** [comment]
amazing, you became chaos 🐒  for GitHub. not bad at all.  glad you can keep moving forward 🏃🏻
