### ISSUE TITLE
Add status action type

### ISSUE THREAD

**Issue by jnwng** [gagoar/use-herald-action#71]
in discussions about what the purpose of the `dryRun` flag is, it was a little confusing as to what it actually does.

however, it is clear that `dryRun` true is the same as `action: none`, which i think is a little more clear in terms of "what happens when this rule passes"

**Comment by gagoar** [comment]
I've been thinking about this option. This will override the action on all the rules that have been defined. is that what you were thinking?

**Comment by gagoar** [comment]
I think the best would be to add another enum to the `action` field in the rule, that clearly states that if the rule does not match, the step will fail. `FAIL_STEP` would be the value
